//
//  UserSettings.swift
//  HarvestTracker
//
//  Created by Luke Browne on 9/29/20.
//  Copyright © 2020 Luke Browne. All rights reserved.
//

import SwiftUI



class UserSettings: ObservableObject {
    
    // UI settings

//    #####  Color Palette by Paletton.com
//    #####  Palette URL: http://paletton.com/#uid=13B0u0kjvD99jTEeWLHnzvHtttk
//
//
//    *** Primary color:
//
//    shade 0 = #5385BD = rgb( 83,133,189) = rgba( 83,133,189,1) = rgb0(0.325,0.522,0.741)
//    shade 1 = #ACCAEB = rgb(172,202,235) = rgba(172,202,235,1) = rgb0(0.675,0.792,0.922)
//    shade 2 = #79A4D5 = rgb(121,164,213) = rgba(121,164,213,1) = rgb0(0.475,0.643,0.835)
//    shade 3 = #356AA5 = rgb( 53,106,165) = rgba( 53,106,165,1) = rgb0(0.208,0.416,0.647)
//    shade 4 = #175499 = rgb( 23, 84,153) = rgba( 23, 84,153,1) = rgb0(0.09,0.329,0.6)

//
//
//    #####  Generated by Paletton.com (c) 2002-2014
    let bgColor = Color(UIColor(hexString: "#5385BD"))
    let lightAccentColor = Color(UIColor(hexString: "#79A4D5"))
    let lightestAccentColor = Color(UIColor(hexString: "#ACCAEB"))
    
    let cardPadding = CGFloat(12)
    let cardShadowRadius = CGFloat(5)
    let buttonShadowRadius = CGFloat(2)
    
    
    // User Settings
    @Published var unitMass: UnitMass
    @Published var unitString: String {
        didSet {
            
            // Save to user defaults
            UserDefaults.standard.set(unitString, forKey: "DefaultUnit")
            
            // Update unitMass
            switch unitString {
            
            case "oz":
                self.unitMass = UnitMass.ounces
            
            case "lb":
                self.unitMass = UnitMass.pounds
            
            case "g":
                self.unitMass = UnitMass.grams
            
            case "kg":
                self.unitMass = UnitMass.kilograms
            
            default:
                self.unitMass = UnitMass.ounces
            
            }
            
        }
    }
    
    init() {
        
        switch UserDefaults.standard.string(forKey: "DefaultUnit") {
        
        case "oz":
            self.unitMass = UnitMass.ounces
            self.unitString = "oz"
            
        case "lb":
            self.unitMass = UnitMass.pounds
            self.unitString = "lb"
            
        case "g":
            self.unitMass = UnitMass.grams
            self.unitString = "g"
            
        case "kg":
            self.unitMass = UnitMass.kilograms
            self.unitString = "kg"
            
        default:
            self.unitMass = UnitMass.ounces
            self.unitString = "oz"
            
        }
    }
    
}
