//
//  UserSettings.swift
//  HarvestTracker
//
//  Created by Luke Browne on 9/29/20.
//  Copyright © 2020 Luke Browne. All rights reserved.
//

import SwiftUI



class UserSettings: ObservableObject {
    
    // UI settings

//    #####  Color Palette by Paletton.com
//    #####  Palette URL: http://paletton.com/#uid=13l0u0kw0w0jyC+oRxVy4oIDfjr
//
//
//    *** Primary color:
//
//       shade 0 = #03899C = rgb(  3,137,156) = rgba(  3,137,156,1) = rgb0(0.012,0.537,0.612)
//       shade 1 = #48A8B5 = rgb( 72,168,181) = rgba( 72,168,181,1) = rgb0(0.282,0.659,0.71)
//       shade 2 = #2793A2 = rgb( 39,147,162) = rgba( 39,147,162,1) = rgb0(0.153,0.576,0.635)
//       shade 3 = #026A79 = rgb(  2,106,121) = rgba(  2,106,121,1) = rgb0(0.008,0.416,0.475)
//       shade 4 = #01535F = rgb(  1, 83, 95) = rgba(  1, 83, 95,1) = rgb0(0.004,0.325,0.373)
//
//
//    #####  Generated by Paletton.com (c) 2002-2014
    let bgColor = Color(UIColor(hexString: "#03899C"))
    
    
    // User Settings
    @Published var unitMass: UnitMass
    @Published var unitString: String {
        didSet {
            
            // Save to user defaults
            UserDefaults.standard.set(unitString, forKey: "DefaultUnit")
            
            // Update unitMass
            switch unitString {
            
            case "oz":
//                print("Default unit set to oz")
                self.unitMass = UnitMass.ounces
            
            case "lb":
//                print("Default unit set to lb")
                self.unitMass = UnitMass.pounds
            
            case "g":
//                print("Default unit set to g")
                self.unitMass = UnitMass.grams
            
            case "kg":
//                print("Default unit set to kg")
                self.unitMass = UnitMass.kilograms
            
            default:
//                print("No default unit chosen")
                self.unitMass = UnitMass.ounces
            
            }
            
        }
    }
    
    init() {
        
        switch UserDefaults.standard.string(forKey: "DefaultUnit") {
        
        case "oz":
            print("Default unit oz")
            self.unitMass = UnitMass.ounces
            self.unitString = "oz"
            
        case "lb":
            print("Default unit lb")
            self.unitMass = UnitMass.pounds
            self.unitString = "lb"
            
        case "g":
            print("Default unit g")
            self.unitMass = UnitMass.grams
            self.unitString = "g"
            
        case "kg":
            print("Default unit kg")
            self.unitMass = UnitMass.kilograms
            self.unitString = "kg"
            
        default:
            print("No default unit chosen")
            self.unitMass = UnitMass.ounces
            self.unitString = "oz"
            
        }
    }
    
}
